const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const studySessionSource = fs.readFileSync(path.join(__dirname, '..', 'studySession.js'), 'utf8');

test('StudySession consumes submission feedback helper output', () => {
  assert.match(
    studySessionSource,
    /(?:from\s+|require\()['"]\.\/studySessionFeedback['"]/,
    'studySession.js should import the study session feedback helper',
  );
  assert.match(
    studySessionSource,
    /parseStudySessionSubmissionResponse\(responseText\)/,
    'studySession.js should parse successful submission responses through the helper',
  );
  assert.match(
    studySessionSource,
    /setSubmissionFeedback\(getStudySessionSubmissionFeedback\(/,
    'studySession.js should store feedback generated by the helper',
  );
  assert.match(
    studySessionSource,
    /\{submissionFeedback\.message\}/,
    'studySession.js should render the helper-produced feedback message',
  );
});
